# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - damage-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_aae3d5b587904fb89ed4132281fb0c60 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_06dd0eae567b4da1990420caf862793f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_aae3d5b587904fb89ed4132281fb0c60 }}/damage-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'damage-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_df2175ab9c4e40c7a3ba82772909d8e8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_aae3d5b587904fb89ed4132281fb0c60 }}/damage-service:${{ github.sha }}'